# Generated by Django 5.2.8 on 2025-11-19 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='cor',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='voltagem',
        ),
        migrations.AddField(
            model_name='produto',
            name='tipo',
            field=models.CharField(choices=[('SMARTPHONE', 'Smartphone'), ('NOTEBOOK', 'Notebook'), ('TABLET', 'Tablet'), ('SMARTTV', 'Smart TV'), ('ACESSORIO', 'Acessório'), ('OUTRO', 'Outro')], default='OUTRO', max_length=20),
        ),
        migrations.AlterField(
            model_name='produto',
            name='especificacoes',
            field=models.TextField(help_text='Descreva processador, RAM, cor, voltagem, etc.', verbose_name='Especificações Técnicas'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='estoque_minimo',
            field=models.IntegerField(default=5),
        ),
    ]
